export const GET_NOW_PLAYING = "GET_NOW_PLAYING";
export const SET_NOW_PLAYING = "SET_NOW_PLAYING";
export const GET_GENRES = "GET_GENRES";
export const SET_GENRES = "SET_GENRES";
export const SET_GENRE_FILTERS = "SET_GENRE_FILTERS";
export const SET_GENRES_AVAILABLE = "SET_GENRES_AVAILABLE"